apiVersion: v1
kind: Service
metadata:
  name: webone-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  type: ClusterIP
  selector:
    app: webone
  sessionAffinity: None
status:
  loadBalancer: {}
